version: '3'
services:
  mongo-db0.01:
    image: mongo:latest
    container_name: mongo-db
    #network_mode: "host"
    restart: always
    ports:
      - 27017:27017
    environment:
      TZ: Asia/Taipei
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin@123
    volumes:
      - ./mongo/db:/data/db
      - /etc/localtime:/etc/localtime
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

#  mongo-express:
#    image: mongo-express:latest
#    container_name: mongo-express
#    restart: always
#    links:
#      - mongo-db0.01:mongo-db0.01
#    depends_on:
#      - mongo-db0.01
#    ports:
#      - 27018:8081
#    environment:
#      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
#      ME_CONFIG_MONGODB_SERVER: mongo-db0.01
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: admin@123
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: admin@123